name: flutterquotes
description: "Daily motivational quotes for you"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.3
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  share_plus: ^8.0.3
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^11.4.0
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  http_parser: ^4.0.2
  retry: ^3.1.0
  uuid: ^4.5.1
  image: ^4.5.3
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/budgeta_script/Budgeta Script.ttf
  fonts:
    - family: BudgetaScript
      fonts:
        - asset: assets/fonts/budgeta_script/Budgeta Script.ttf
